### PR TITLE
Use fully-resolved import paths

### LINKED ISSUE #19: Webpack can't resolve imported Gia files due to missing .js extension
After upgrading Swup to v4 and gia-plugin to v2.0.1, the code no longer compiles with webpack (laravel-mix).
I get the following errors: 

errors

I have found out that this is caused by the lack of the **.js** extension in the import statements of this plugin:
```
import t from "gia/loadComponents";
import n from "gia/removeComponents";
import s from "gia/config";
```

Setting the `fullySpecified` option (defaults to true) in webpack resolves the compilation problem:
```
module: {
      rules: [
        {
          test: /\.m?js$/,
          resolve: {
            fullySpecified: false, // disable the behaviour
          },
        },
      ],
    },
```
However, now there's a runtime error:
TypeError: gia_config_js__WEBPACK_IMPORTED_MODULE_3__.set is not a function.

The only thing that solves it for me is adding the **.js** extensions to the import statements.
Can those be added in?
Thanks,
Luca

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Fully resolve import paths to `gia` to fix bundling issues for consumers

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [ ] ~~All tests are passing (`npm run test`)~~
- [ ] ~~New or updated tests are included~~
- [ ] ~~The documentation was updated as required~~

**Additional information**

Hopefully closes #19

### CODE REVIEW

**Review by hirasso — APPROVED** [review]
👏
