### ISSUE TITLE
Webpack can't resolve imported Gia files due to missing .js extension

### ISSUE THREAD

**Issue by jaxtheking** [swup/gia-plugin#19]
After upgrading Swup to v4 and gia-plugin to v2.0.1, the code no longer compiles with webpack (laravel-mix).
I get the following errors: 

![errors](https://github.com/swup/gia-plugin/assets/3924723/ffe5e4b1-fbbb-41ed-ad27-04b9279078b6)

I have found out that this is caused by the lack of the **.js** extension in the import statements of this plugin:
```
import t from "gia/loadComponents";
import n from "gia/removeComponents";
import s from "gia/config";
```

Setting the `fullySpecified` option (defaults to true) in webpack resolves the compilation problem:
```
module: {
      rules: [
        {
          test: /\.m?js$/,
          resolve: {
            fullySpecified: false, // disable the behaviour
          },
        },
      ],
    },
```
However, now there's a runtime error:
TypeError: gia_config_js__WEBPACK_IMPORTED_MODULE_3__.set is not a function.

The only thing that solves it for me is adding the **.js** extensions to the import statements.
Can those be added in?
Thanks,
Luca

**Comment by daun** [comment]
I have a feeling that this should be tackled at the root, by correctly defining ESM exports in `gia` itself. But we don't have easy access to the repo, so if adding the .js extensions here in the plugin works as well, let's try that first.

**Comment by daun** [comment]
Version 2.0.2 of the plugin should land on npm in a few seconds. That should fix your issue by adding file extensions to import paths. Let us know if it doesn't!

**Comment by jaxtheking** [comment]
Hi @daun,
thanks for the prompt response! Unfortunately the plugin is not working at all due to runtime errors.

When I import your npm package (`import SwupGiaPlugin from '@swup/gia-plugin';`), runtime errors raise every time one of the imported functions (config, loadComponents, removeComponents) are called.
However, if I include your plugin's source code directly into my project, v2.0.2 works perfectly with no runtime errors.

I cloned your repo and investigated further. It does not matter what I do, the gia functions import as ESM objects ({'__esModule': true, 'default': f}) and never resolve to their default value (function).
You might be right, it may depend on the ESM exports in gia (then again, your plugin works fine as part of my project) but I suspect something in the microbundle setup.

Either way, the solution is easy yet inelegant: `.default` must be appended to each imported function's name (i.e. config.default.set instead of config.set).
This will definitely fix the issues.

**Comment by jaxtheking** [comment]
FYI
```
import Plugin from '@swup/plugin';
import loadComponents from 'gia/loadComponents.js';
import removeComponents from 'gia/removeComponents.js';
import config from 'gia/config.js';

export default class SwupGiaPlugin extends Plugin {
	name = 'SwupGiaPlugin';

	requires = { swup: '>=4' };

	defaults = {
		components: {},
		firstLoad: true,
		log: false
	};

	get containers() {
		const selector = this.swup.visit.containers.join(', ');
		return Array.from(document.querySelectorAll(selector));
	}

	constructor(options = {}) {
		super();
		this.options = { ...this.defaults, ...options };
	}

	mount() {
		config.default.set('log', this.options.log);
		// This would work too.
		// const config = require('gia/config.js').default;

		this.before('content:replace', this.unloadComponents);
		this.on('content:replace', this.mountComponents);

		if (this.options.firstLoad) {
			this.mountComponents();
		}
	}

	unmount() {
		super.unmount();
		this.unloadComponents();
	}

	mountComponents() {
		const { components } = this.options;
		this.containers.forEach((container) => loadComponents.default(components, container));
	}

	unloadComponents() {
		this.containers.forEach((container) => removeComponents.default(container));
	}
}
```

**Comment by jaxtheking** [comment]
Sorry @daun, have you had the chance to review this at all?

**Comment by daun** [comment]
@jaxtheking No, haven't had a good chance as I've been away from the keyboard. I'll look into this later today or this week.

**Comment by daun** [comment]
I have a feeling it's related to TypeScript's `esModuleInterop` compiler option. Just leaving this here as a note for later.

**Comment by daun** [comment]
@jaxtheking Can you try version 2.0.3 and let us know if this is fixed?

**Comment by hirasso** [comment]
I think it isn't fixed. Just tested it locally

**Comment by daun** [comment]
@hirasso Can you post the exact error?

**Comment by hirasso** [comment]
It's the same as above:

> TypeError: gia_config_js__WEBPACK_IMPORTED_MODULE_3__.set is not a function.

It's caused by the import paths in `@swup/gia-plugin`:
```js
import loadComponents from 'gia/loadComponents.js';
import removeComponents from 'gia/removeComponents.js';
import config from 'gia/config.js';
```
If you change that to the following, it starts working:
```js
import loadComponents from 'gia/dist/loadComponents.js';
import removeComponents from 'gia/dist/removeComponents.js';
import config from 'gia/dist/config.js';
```
Gia seems a bit messy to me – we should probably try and fix it on their end. But we don't have writing rights, do we? Maybe best to talk it through in a quick call.

**Comment by jaxtheking** [comment]
I can confirm it doesn't work.
The solution suggested by @hirasso seems a reasonable temporary fix until the issue is fixed on Gia's end?

**Comment by daun** [comment]
@hirasso What do you think? Should we just merge your workaround in the `fix/gia-imports` branch?

**Comment by hirasso** [comment]
Let's try it and see what happens. Hopefully, the files under `/dist` actually have the same features like the toplevel files.

**Comment by hirasso** [comment]
@jaxtheking we've released an attempted fix in https://github.com/swup/gia-plugin/releases/tag/2.0.4. Could you test if it works for you now?

**Comment by jaxtheking** [comment]
I can confirm v2.0.4 works. No more runtime errors and components do load and remove correctly as one navigates across pages.

However, since I import gia files elsewhere in my project, my bundle now contains two versions of the 3 files imported by this plugin; one from the `gia/dist/` (5x larger) and one from `gia/`. I'm just pointing it out, this is completely trivial due to the negligible file sizes.

![gia_imports](https://github.com/swup/gia-plugin/assets/3924723/a1c92820-a5b7-4ea4-86aa-387272116b13)

I'm still perplexed as to why if I copy the index.js file from version 2.0.2 and include it directly into my project, the files are not imported as modules and it all works without errors!?
Anyway, thanks for the fix!

**Comment by daun** [comment]
I'll close this as resolved. That's probably the best we can do on our end.
